export const researchTaskRegisterPath =
  "00 Project Admin/30 Task Register.yaml" as const;

export const researchProjectUniversalStructure = [
  [".scratch", "directory"],
  ["00 Project Admin", "directory"],
  ["00 Project Admin/00 Project Profile.md", "file"],
  ["00 Project Admin/10 Project Definition.yaml", "file"],
  ["00 Project Admin/20 Source Register.yaml", "file"],
  [researchTaskRegisterPath, "file"],
  ["00 Project Admin/40 Research Map.yaml", "file"],
  ["00 Project Admin/50 Deliverable Register.yaml", "file"],
  ["00 Project Admin/60 Contribution and AI Use.md", "file"],
  ["10 Source Materials", "directory"],
  ["10 Source Materials/10 Programme and Project", "directory"],
  ["10 Source Materials/20 Core Sources", "directory"],
  ["10 Source Materials/30 Reference Sources", "directory"],
  ["10 Source Materials/references.bib", "file"],
  ["20 Supervisor Meetings", "directory"],
  ["30 Deliverables", "directory"],
  ["70 Research", "directory"],
  ["70 Research/10 Reading", "directory"],
  ["70 Research/20 Mathematics", "directory"],
  ["70 Research/30 Experiments", "directory"],
  ["70 Research/CLAIMS.md", "file"],
  ["70 Research/GLOSSARY.md", "file"],
  ["70 Research/QUESTIONS.md", "file"],
  ["70 Research/templates", "directory"],
  ["70 Research/templates/deliverable-check.md", "file"],
  ["70 Research/templates/experiment-record.md", "file"],
  ["70 Research/templates/mathematics-note.tex", "file"],
  ["70 Research/templates/meeting-note.md", "file"],
  ["70 Research/templates/reading-note.md", "file"],
  ["90 Resources", "directory"],
  ["90 Resources/00 Unclassified", "directory"],
  ["AGENTS.md", "file"],
  ["CLAUDE.md", "file"],
  ["CONTEXT.md", "file"],
  ["docs", "directory"],
  ["docs/00 Structure and Naming.md", "file"],
  ["docs/10 Sources and Provenance.md", "file"],
  ["docs/20 Research Procedure.md", "file"],
  ["docs/30 Deliverables Procedure.md", "file"],
  ["docs/adr", "directory"],
] as const satisfies ReadonlyArray<readonly [string, "directory" | "file"]>;

export const urecaResearchProjectStructure = [
  ["30 Deliverables/10 Abstract", "directory"],
  ["30 Deliverables/20 Poster", "directory"],
  ["30 Deliverables/30 Paper", "directory"],
  ["30 Deliverables/40 Reflection", "directory"],
  ["90 Resources/10 Preparation Archive", "directory"],
  ["90 Resources/20 Research Aids", "directory"],
] as const satisfies ReadonlyArray<readonly [string, "directory" | "file"]>;
