export const universalStructurePaths = [
  ["00 Module Admin", "directory"],
  ["00 Module Admin/00 Module Profile.md", "file"],
  ["00 Module Admin/10 Module Definition.yaml", "file"],
  ["00 Module Admin/20 Curation Register.jsonl", "file"],
  ["00 Module Admin/30 Task Register.yaml", "file"],
  ["00 Module Admin/40 Source Map.yaml", "file"],
  ["00 Module Admin/50 Textbook Register.yaml", "file"],
  ["10 Learning Materials", "directory"],
  ["10 Learning Materials/10 Lecture Materials", "directory"],
  ["10 Learning Materials/20 Textbook Chapters", "directory"],
  ["10 Learning Materials/30 Personal Notes", "directory"],
  ["20 Tutorials", "directory"],
  ["30 Assessments", "directory"],
  ["30 Assessments/30 Midterms", "directory"],
  ["30 Assessments/40 Finals", "directory"],
  ["40 Projects and Labs", "directory"],
  ["70 Learning", "directory"],
  ["90 Resources", "directory"],
  ["90 Resources/00 Unclassified", "directory"],
  [".scratch", "directory"],
  ["NTULearn", "directory"],
  ["AGENTS.md", "file"],
  ["CLAUDE.md", "file"],
  ["CONTEXT.md", "file"],
  ["docs", "directory"],
  ["docs/00 Structure and Naming.md", "file"],
  ["docs/10 Curation Procedure.md", "file"],
  ["docs/20 Teaching Procedure.md", "file"],
  ["docs/30 Textbook Procedure.md", "file"],
  ["docs/adr", "directory"],
] as const satisfies ReadonlyArray<readonly [string, "directory" | "file"]>;
