#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8
TOTAL_MINUTES=30

banner "academic-os Calendar bootstrap"

HOME_DIR="$(cd ~ && pwd)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SECRETS_DIR="${ACADEMIC_OS_SECRETS_DIR:-$HOME_DIR/.config/academic-os}"
CONFIG_PATH="${ACADEMIC_OS_CONFIG_PATH:-$SECRETS_DIR/academic-os.config.json}"
READ_CLIENT_PATH="$SECRETS_DIR/calendar-read-client.json"
WRITE_CLIENT_PATH="$SECRETS_DIR/calendar-write-client.json"
READ_CREDENTIAL_PATH="$SECRETS_DIR/calendar-read.credentials.json"
WRITE_CREDENTIAL_PATH="$SECRETS_DIR/calendar-write.credentials.json"
READ_SCOPES="https://www.googleapis.com/auth/calendar.calendarlist.readonly,https://www.googleapis.com/auth/calendar.events.readonly"
WRITE_SCOPES="https://www.googleapis.com/auth/calendar.calendars,https://www.googleapis.com/auth/calendar.events"

require_command() {
  command -v "$1" >/dev/null 2>&1 || {
    warn "required command is unavailable: $1"
    exit 1
  }
}

validate_client_file() {
  jq -e '.installed.client_id and .installed.client_secret and .installed.project_id' \
    "$1" >/dev/null
}

validate_user_credentials() {
  jq -e '.type == "authorized_user" and (.refresh_token | type == "string" and length > 0)' \
    "$1" >/dev/null
}

prompt_value() {
  local variable="$1" prompt="$2" default_value="$3" input
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -r input || true
  [[ -z "$input" ]] && input="$default_value"
  printf -v "$variable" '%s' "$input"
}

authorize_user_credentials() {
  local role="$1" client_path="$2" scopes="$3" output_path="$4"

  if [[ -e "$output_path" ]]; then
    if ! confirm "Replace the existing $role credential file?"; then
      validate_user_credentials "$output_path" || {
        warn "existing credential is not a valid authorized-user file: $output_path"
        exit 1
      }
      note "kept existing $role credential file"
      return 0
    fi
  fi

  say "A browser approval page will open for the $role Calendar scopes."
  step "Approve only after checking the requested scope level; return here when Google finishes."
  node "$REPO_ROOT/scripts/authorize-calendar-credentials.mjs" \
    --role "$role" \
    --client "$client_path" \
    --scopes "$scopes" \
    --output "$output_path"
  validate_user_credentials "$output_path" || {
    warn "OAuth helper produced an unexpected credential format"
    exit 1
  }
  note "stored $role user credential at $output_path"
}

write_private_config() {
  local horizon="$1" temporary
  temporary=$(mktemp "$SECRETS_DIR/academic-os.config.json.XXXXXX")
  jq \
    --arg horizon "$horizon" \
    --arg read_path "$READ_CREDENTIAL_PATH" \
    --arg write_path "$WRITE_CREDENTIAL_PATH" \
    '.calendar = {
      managementHorizon: $horizon,
      credentials: {
        scheduledRead: $read_path,
        interactiveWrite: $write_path
      }
    }' \
    "$CONFIG_PATH" > "$temporary"
  chmod 600 "$temporary"
  mv "$temporary" "$CONFIG_PATH"
}

run_cli() {
  (cd "$REPO_ROOT" && node dist/src/cli.js "$@")
}

stage "Check private inputs" 2
require_command jq
require_command node
require_command npm
[[ -f "$CONFIG_PATH" ]] || { warn "private config is missing: $CONFIG_PATH"; exit 1; }
[[ -f "$READ_CLIENT_PATH" ]] || { warn "read OAuth client is missing: $READ_CLIENT_PATH"; exit 1; }
[[ -f "$WRITE_CLIENT_PATH" ]] || { warn "write OAuth client is missing: $WRITE_CLIENT_PATH"; exit 1; }
validate_client_file "$READ_CLIENT_PATH" || { warn "invalid read OAuth client JSON"; exit 1; }
validate_client_file "$WRITE_CLIENT_PATH" || { warn "invalid write OAuth client JSON"; exit 1; }
chmod 700 "$SECRETS_DIR"
chmod 600 "$READ_CLIENT_PATH" "$WRITE_CLIENT_PATH" "$CONFIG_PATH"
say "Private config and both Desktop OAuth client files are present."
note "No credential contents are printed or committed."

stage "Authorize Calendar read access" 5
pause "Press Enter to start the read-only Google approval"
authorize_user_credentials "read" "$READ_CLIENT_PATH" "$READ_SCOPES" "$READ_CREDENTIAL_PATH"

stage "Authorize Calendar write access" 5
pause "Press Enter to start the interactive-write Google approval"
authorize_user_credentials "write" "$WRITE_CLIENT_PATH" "$WRITE_SCOPES" "$WRITE_CREDENTIAL_PATH"

stage "Configure private academic-os Calendar paths" 3
default_horizon="$(TZ=Asia/Singapore date '+%Y-%m-%dT00:00:00+08:00')"
current_drive_mount=$(jq -er '.driveMount' "$CONFIG_PATH")
current_state_root=$(jq -er '.stateRoot' "$CONFIG_PATH")
management_horizon=""
say "Existing Drive mount: $current_drive_mount"
say "Existing private state root: $current_state_root"
prompt_value management_horizon "Management horizon (Enter for $default_horizon):" "$default_horizon"
write_private_config "$management_horizon"
note "Updated only the private calendar block in $CONFIG_PATH."

stage "Preview Owned-calendar setup" 3
(cd "$REPO_ROOT" && npm run build)
say "The next report is read-only; it will not create calendars."
run_cli calendar setup --config "$CONFIG_PATH" --json

stage "Apply reviewed calendar setup" 3
say "Review the preview above. Only missing secondary calendars may be created."
if confirm "Create the previewed Commitments/Routine calendars and persist exact IDs?"; then
  run_cli calendar setup --config "$CONFIG_PATH" --apply --json
else
  warn "calendar creation was not approved; stopping before any Google write"
  finish
  exit 0
fi

stage "Initial pull-only Calendar Refresh" 3
say "This reads the three Owned calendars and writes only private mirror state."
run_cli calendar refresh --config "$CONFIG_PATH" --json

stage "Install daily local Refresh" 6
say "This installs a per-user macOS LaunchAgent at 05:00 Asia/Singapore."
if confirm "Install the Calendar Refresh LaunchAgent now?"; then
  (cd "$REPO_ROOT" && node scripts/install-calendar-refresh-launchd.mjs --config "$CONFIG_PATH")
else
  note "LaunchAgent installation skipped; it can be run later from the operator guide."
fi

say "Routine/event migration is intentionally not performed by this wizard."
note "We will review exact live series and require a separate explicit Promotion approval."

finish
